### ISSUE TITLE
No icon and/or tooltip

### ISSUE THREAD

**Issue by Holmelund** [Monteo/SuperMacro#3]
Icon and tooltip doesn't seem to work with bongos bars.

**Comment by xcinderz** [comment]
DId you try this?

If you want see tooltips and button text for spell in macros you should add line to top of your macro:
/run -- CastSpellByName("Spell Name")
/script -- CastSpellByName("Spell Name")
/script if nil then CastSpellByName("SPELLNAME"); end
/run -- cast("Spell Name")
/script -- cast("Spell Name")
