### ISSUE TITLE
Question about SuperMacro future...

### ISSUE THREAD

**Issue by FireReaver** [Monteo/SuperMacro#4]
Hi, sorry to bother you in this (hateful) way, but I don't have any other means to contact you since I haven't found any useful email here to do that.

My question is: are you planning to make a new SuperMacro branch addon when Classic WoW comes out? (it seems it will be based on Legion API so far, but nothing can be confirmed at the moment and there still is the chance Blizzard will use the 1.12.1 API for that, I hope for the latter to be honest)
I love SuperMacro and I'd really like to use it when that happens, since it has become a mandatory addon for me to have in Vanilla.

Waiting for an answer,
Thank you,

FireReaver

**Comment by Monteo** [comment]
Hi, Blizzard will use the 70300 API
