### ISSUE TITLE
Feature request: assist players into adding links in the macros

### ISSUE THREAD

**Issue by FrostShock** [Monteo/SuperMacro#6]
When I need to add an item link or a quest link, I have to follow a certain procedure which is not the easiest thing to do. I've learned about it [from this forum thread](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/wow-ui-macros-talent-specs/238813-how-link-any-item-macro.html)

So I would like to ask for implementing this feature: help the player to add links to the items in their inventory in the macros. When they push a button or hotkey, clicking on an item will add the link to that item in the macro they are currently editing.

Thank you

**Comment by Monteo** [comment]
complete
