### ISSUE TITLE
Issue pasting large macros 

### ISSUE THREAD

**Issue by lvangh** [Monteo/SuperMacro#7]
I'm having an issue where very large macros are not pasting into the right-side SM code form. Around 2500+ characters the macro just stops with "..." and blank characters are entered if you try to type. 

![image](https://user-images.githubusercontent.com/19690096/56870865-9d9af800-69ca-11e9-8e2c-8c2c9b050b8a.png)

I've tried:
-Updating to 3.16a
-Clearing all Supermacro LUA
-Going back to 3.16

The only workaround I've found is pasting the code in chunks of 1000 characters etc, pressing enter to put a new \CR, then pasting another chunk of code, repeat. 

I could demonstrate this behavior in a discord call screen share if needed.

*EDIT
OK, so apparently macros still run fine, all the text is just gone. Maybe a limitation of the WoW text box?

**Comment by Monteo** [comment]
paste here your macro

**Comment by Monteo** [comment]
try it
go to menu>Macros>>Regular>new *** macro
Enter Macro Commands:

/script lvangh()

Enter Extended LUA code:

function lvangh()
*macro body*

Save macro, save extend

**Comment by lvangh** [comment]
Thank you, it seems to be a visual bug. Even if you see "..." the  macros still work. I ended up converting the code to an addon, so no more limitations. Thank you again,. 

Are you going to forward/back/port to 1.13?

**Comment by Monteo** [comment]
In 1.13 there will be macros as in the actual

**Comment by Monteo** [comment]
no, it doesn't make any practical sense.
